name: Generate Snake

on:
  # Roda automaticamente todo dia à meia-noite
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite rodar manualmente na aba "Actions"
  workflow_dispatch:

  # Roda a cada push na branch master/main
  push:
    branches:
    - master
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Gera a animação da cobrinha
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Envia os arquivos gerados para a branch "output"
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
